kind: pipeline
name: masak

platform:
  os: linux
  arch: amd64

steps:
- name: nasgor
  image: rzlamrr/dvstlab:latest
  environment:
    PAT:
      from_secret: PAT
    TOKED:
      from_secret: TOKED
    ID:
      from_secret: ID
    HASH:
      from_secret: HASH
  commands:
  - rm -rf .git
  - bash install.sh
  - bash rec.sh
